close all
clear variables
clc
%% EDIT FILE PATH
%to set the top directory you have saved the code in
TopPath = 'D:/Cerian/OneDrive - University of Cambridge/UrbanTreeModel/ModelCodeForPublic2023/UrbanEpidemicModel2023/';
MyFileExchangeFiles_m_Map = 'D:/Cerian/OneDrive - University of Cambridge/MatlabFileExchange/m_map';
%%
addpath(MyFileExchangeFiles_m_Map);
%% EDIT PREVALENCE OF SPECIES OF INTEREST 
% proportion of trees at roadside and in parks that are of species of interest (expert opinion or some other method)
ProportionSpeciesXRoad = 0.2;
ProportionSpeciesXPark = 0.15; 
%% EDIT IF WANT TO GENERATE FEWER/MORE LANDSCAPES
NumLandscapesToGenerate = 4;

%%
cd([TopPath,'dataprepare']) 

addpath('src_shp');
pathToNTMRoadsideShapeFile = 'shapeFiles/ntm/NTM_RoadTrees';
pathToNTMParkGardenShapeFile = 'shapeFiles/ntm/NTM_ParkTrees';

% the function 'generateSyntheticDatasets' is stored in .../urbanEpidemicModel/dataPrepare/src_shp 


%% Method 1: Random
generateSyntheticDatasets2023(NumLandscapesToGenerate,'speciesAssignmentType.UnknownRandomly' ,  ...
    'SyntheticDatasets/UnknownRandom', ...
    'synth_Random_', ...
    pathToNTMRoadsideShapeFile, ...
    pathToNTMParkGardenShapeFile, ...
    ProportionSpeciesXRoad, ...
    ProportionSpeciesXPark)
 close all

%% Method 2: Matern Poisson
generateSyntheticDatasets2023(NumLandscapesToGenerate, 'speciesAssignmentType.UnknownMaternPoisson',  ...
    'SyntheticDatasets/UnknownMaternPoisson', ...
    'synth_Matern_', ...
    pathToNTMRoadsideShapeFile, ...
    pathToNTMParkGardenShapeFile, ...
    ProportionSpeciesXRoad, ...
    ProportionSpeciesXPark)

%% Method 3: Assign all trees to species X
generateSyntheticDatasets2023(1, 'speciesAssignmentType.assignAllToSpeciesX',  ...
    'SyntheticDatasets/AllTrees', ...
    'synth_All_', ...
    pathToNTMRoadsideShapeFile, ...
    pathToNTMParkGardenShapeFile, ...
    ProportionSpeciesXRoad, ...
    ProportionSpeciesXPark)
%%
load chirp
sound(y,Fs/2)